name: Hello World

on: 
  push:

defaults:
  run:
    shell: bash

jobs:
  greet:
    name: Greet
    runs-on: ubuntu-latest
    steps: 
      - name: Say Hello
        run: echo "Hello World"
  execute:
    name: Execute shell script
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          now=$(date "+%Y-%m-%d %H:%M:%S")
          echo "Hello $USER, it is $now!"

      - name: Python Script
        shell: python
        run: |
          import os
          from datetime import datetime

          user = os.environ.get("USER") or os.environ.get("USERNAME") or "runner"
          print(f"Hello {user}, it is {datetime.now()}!")
