name: On Push


on:
  push:

defaults:
  run:
    shell: bash

jobs:
  hello:
    name: Hello
    uses: ./.github/workflows/hello.yml

  system:
    name: System
    uses: ./.github/workflows/system.yml
