name: System Information

on:
  push:

jobs:
  system:
    name: System Information
    runs-on: ubuntu-latest
    steps:
      - name: Show current working directory
        run: ls -la

      - name: Who am I?
        run: whoami

      - name: Show home directory
        run: ls -la ~

   directory:
     name: Working Directory
     runs-on: ubuntu-latest
     steps:
       - run: echo "$PWD" && ls -la
       - run: mktemp --tempdir="$PWD"
       - run: ls -la
